services:
  frc-elo-app:
    build: .
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      BASIC_AUTH_USER: ${BASIC_AUTH_USER}
      BASIC_AUTH_PASS: ${BASIC_AUTH_PASS}
    ports:
      - "8080:3000"
    networks:
      - frcspieldaten_default
      - nginx-proxy-manager_default

networks:
  frcspieldaten_default:
    external: true
  nginx-proxy-manager_default:
    external: true
